### ISSUE TITLE
I am not able to work it out with ionic framework

### ISSUE THREAD

**Issue by gauravshegokar** [gavruk/angular-card#16]
heres example.js
<ion-view title="Add Card/NFC">
    <ion-content overflow-scroll="true" padding="true" class="has-header">
  <body data-ng-app="app" data-ng-controller="ExampleCtrl">

```
<form action="#"
  name="cardForm"
  data-card
  data-width="500"
  data-card-container="#card-container"
  data-placeholders="cardPlaceholders"
  data-options="cardOptions"
  data-messages="cardMessages"
  >

  <div>
      <input placeholder="Card number" type="text" name="CardNumber" card-number data-ng-model="card.number" />

      <input placeholder="Full name" type="text" name="CardName" card-name data-ng-model="card.name" />
  </div>
  <div>
      <input placeholder="MM / YYYY" type="text" name="CardExpiry" card-expiry data-ng-model="card.expiry" />

      <input placeholder="CVC" type="text" name="CardCvc" card-cvc data-ng-model="card.cvc" />

      <input type="button" value="Change card" data-ng-click="changeCard()" />
      <input type="button" value="Clear" data-ng-click="clear()" />
  </div>

</form>

<div id="card-container"></div>

<script src="lib/card/lib/js/card.js" type="text/javascript"></script>
```

  </body>
</ion-content>
</ion-view>

stack trace 
: TypeError: Card is not a function
    at link (http://localhost:8100/lib/angular-card/src/card.js:82:9)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:17476:44
    at invokeLinkFn (http://localhost:8100/lib/ionic/js/ionic.bundle.js:17482:9)
    at nodeLinkFn (http://localhost:8100/lib/ionic/js/ionic.bundle.js:16982:11)
    at compositeLinkFn (http://localhost:8100/lib/ionic/js/ionic.bundle.js:16373:13)
    at compositeLinkFn (http://localhost:8100/lib/ionic/js/ionic.bundle.js:16377:13)
    at publicLinkFn (http://localhost:8100/lib/ionic/js/ionic.bundle.js:16248:30)
    at self.appendViewElement (http://localhost:8100/lib/ionic/js/ionic.bundle.js:52345:5)
    at Object.switcher.render (http://localhost:8100/lib/ionic/js/ionic.bundle.js:50456:41)
    at Object.switcher.init (http://localhost:8100/lib/ionic/js/ionic.bundle.js:50376:20) <form action="#" name="cardForm" data-card="" data-width="500" data-card-container="#card-container" data-placeholders="cardPlaceholders" data-options="cardOptions" data-messages="cardMessages" class="ng-pristine ng-valid">

i think card.js is not available to controller

**Comment by gauravshegokar** [comment]
solved..!
added script file to index.html
