### ISSUE TITLE
Unknown provider: $cardProvider <- $card <- cardNumberDirective

### ISSUE THREAD

**Issue by tambovchanin** [gavruk/angular-card#22]
Get all code from example but it is not working.

Only example - working well, but in real project - generate an error.
Could you help?

**Comment by tambovchanin** [comment]
```
angular.js:11607 Error: [$injector:unpr] http://errors.angularjs.org/1.3.13/$injector/unpr?p0=%24cardProvider%20%3C-%20%24card%20%3C-%20cardNumberDirective
    at Error (native)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.min.js:6:417
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.min.js:38:7
    at Object.d [as get] (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.min.js:36:13)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.min.js:38:81
    at d (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.min.js:36:13)
    at Object.e [as invoke] (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.min.js:36:283)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.min.js:47:393
    at s (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.min.js:7:302)
    at Object.<anonymous> (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.min.js:47:360)
```

**Comment by tambovchanin** [comment]
Resolve
